start-bridge:
    docker run -d --restart always --name dante-bridge \
        -p 1080:1080 \
        --network ipfs_client_network \
        --ip 172.19.0.3 \
        --cap-add NET_ADMIN \
        --mount type=bind,source=./dante.conf,target=/etc/sockd.conf \
        --mount type=bind,source=./generate.sh,target=/generate.sh \
        -v ./log:/var/log \
        jmfrank63/dante:latest
    docker network connect ipfs_server_network --ip 172.18.0.3 dante-bridge
    docker run -it --rm --volumes-from dante-bridge jmfrank63/dante:latest /generate.sh

stop-bridge:
    docker stop dante-bridge || true
    docker network disconnect ipfs_server_network dante-bridge || true
    docker network disconnect ipfs_client_network dante-bridge || true

remove-bridge: stop-bridge
    docker rm dante-bridge || true

build:
    docker build -t dante:latest .

tag:
    docker tag dante:latest jmfrank63/dante:latest

push: build tag
    docker push jmfrank63/dante:latest
