package loader

import (
pluginbadgerds "github.com/ipfs/kubo/plugin/plugins/badgerds"
pluginclient "github.com/ipfs/kubo/plugin/plugins/client"
pluginflatfs "github.com/ipfs/kubo/plugin/plugins/flatfs"
pluginfxtest "github.com/ipfs/kubo/plugin/plugins/fxtest"
pluginiplddagjose "github.com/ipfs/kubo/plugin/plugins/dagjose"
pluginipldgit "github.com/ipfs/kubo/plugin/plugins/git"
pluginlevelds "github.com/ipfs/kubo/plugin/plugins/levelds"
pluginpeerlog "github.com/ipfs/kubo/plugin/plugins/peerlog"
pluginserver "github.com/ipfs/kubo/plugin/plugins/server"
)


// DO NOT EDIT THIS FILE
// This file is being generated as part of plugin build process
// To change it, modify the plugin/loader/preload.sh

func init() {
	Preload(pluginipldgit.Plugins...)
	Preload(pluginiplddagjose.Plugins...)
	Preload(pluginbadgerds.Plugins...)
	Preload(pluginflatfs.Plugins...)
	Preload(pluginlevelds.Plugins...)
	Preload(pluginpeerlog.Plugins...)
	Preload(pluginfxtest.Plugins...)
	Preload(pluginclient.Plugins...)
	Preload(pluginserver.Plugins...)
}
