build:
    #!/usr/bin/env bash
    set -e
    TARGETARCH=$(uname -m)
    (cd ..
    docker build -f client/Dockerfile -t clientlib_builder .
    )
    docker create --name clientlib_container clientlib_builder
    mkdir -p ../../plugin/plugins/client/lib
    if [ "$TARGETARCH" = "x86_64" ]; then \
    docker cp clientlib_container:/rustlib/target/x86_64-unknown-linux-gnu/release/libclient.so  ../../plugin/plugins/client/lib/libclient.so; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
    docker cp clientlib_container:/rustlib/target/aarch64-unknown-linux-gnu/release/libclient.so  ../../plugin/plugins/client/lib/libclient.so; \
    fi

clean:
    docker rm clientlib_container || true
    docker rmi clientlib_builder || true
