stop-all-nodes:
    cd server && just stop-all-server
    cd client && just stop-all-client

remove-all-nodes:
    cd server && just remove-all-server
    cd client && just remove-all-client

start-all-nodes:
    cd server && just start-all-server
    cd client && just start-all-client

restart-all-nodes:
    cd server && just restart-all-server
    cd client && just restart-all-client

renew-all-nodes:
    cd server && just renew-all-server
    cd client && just renew-all-client

run-all-nodes:
    cd server && just run-all-server
    cd client && just run-all-client

create-all-networks:
    cd server && just create-ipfs-server-network
    cd client && just create-ipfs-client-network
